// constants/alumniMockData.js

export const ALUMNI_MOCK_DATA = [
  {
    id: 1,
    name: "Ahmed Khan",
    graduationYear: "2018",
    department: "Computer Science",
    currentPosition: "Senior Software Engineer",
    company: "Google",
    location: "San Francisco, USA",
    expertise: ["Machine Learning", "Cloud Computing", "React"],
    avatar: "AK",
  },
  {
    id: 2,
    name: "Sara Ali",
    graduationYear: "2019",
    department: "Software Engineering",
    currentPosition: "Product Manager",
    company: "Microsoft",
    location: "Seattle, USA",
    expertise: ["Product Strategy", "Agile", "UX Design"],
    avatar: "SA",
  },
  {
    id: 3,
    name: "Hassan Raza",
    graduationYear: "2020",
    department: "Computer Science",
    currentPosition: "Tech Lead",
    company: "Amazon",
    location: "Dubai, UAE",
    expertise: ["Full Stack", "DevOps", "AWS"],
    avatar: "HR",
  },
  {
    id: 4,
    name: "Fatima Hussain",
    graduationYear: "2017",
    department: "Electrical Engineering",
    currentPosition: "Hardware Engineer",
    company: "Intel",
    location: "California, USA",
    expertise: ["VLSI Design", "Embedded Systems", "IoT"],
    avatar: "FH",
  },
  {
    id: 5,
    name: "Usman Malik",
    graduationYear: "2021",
    department: "Software Engineering",
    currentPosition: "Data Scientist",
    company: "Facebook (Meta)",
    location: "London, UK",
    expertise: [
      "Data Analytics",
      "Python",
      "TensorFlow",
      "TensorFlow",
      "TensorFlow",
    ],
    avatar: "UM",
  },
  {
    id: 6,
    name: "Ayesha Tariq",
    graduationYear: "2016",
    department: "Business Administration",
    currentPosition: "Marketing Director",
    company: "Unilever",
    location: "Karachi, Pakistan",
    expertise: [
      "Digital Marketing",
      "Brand Strategy",
      "Analytics",
      "TensorFlow",
    ],
    avatar: "AT",
  },
  {
    id: 7,
    name: "Bilal Ahmed",
    graduationYear: "2019",
    department: "Computer Engineering",
    currentPosition: "Cybersecurity Analyst",
    company: "Cisco",
    location: "Toronto, Canada",
    expertise: ["Network Security", "Penetration Testing", "Cryptography"],
    avatar: "BA",
  },
  {
    id: 8,
    name: "Zainab Sheikh",
    graduationYear: "2022",
    department: "Computer Science",
    currentPosition: "Frontend Developer",
    company: "Spotify",
    location: "Stockholm, Sweden",
    expertise: ["React", "TypeScript", "UI/UX"],
    avatar: "ZS",
  },
  {
    id: 9,
    name: "Zainab Sheikh",
    graduationYear: "2022",
    department: "Computer Science",
    currentPosition: "Frontend Developer",
    company: "Spotify",
    location: "Stockholm, Sweden",
    expertise: [
      "Digital Marketing",
      "Digital Marketing",
      "Digital Marketing",
      "Digital Marketing",
      "Digital Marketing",
    ],
    avatar: "ZS",
  },
];
